[package]
name = "kkrpc-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.74"
futures = "0.3.30"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["full"] }
uuid = { version = "1.6.1", features = ["v4"] }
