# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: GitHub Package Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
      - uses: pnpm/action-setup@v4
      - run: |
          pnpm install
          pnpm build
      - run: npm publish --access public
        working-directory: ./packages/kkrpc
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
